[package]
name = "learn"
version = "0.1.0"
authors = ["Max Block <maxblock@pm.me>"]
edition = "2018"

[dependencies]
handlebars = "3.4.0"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"